### ISSUE TITLE
sticky 组件使用报错

### ISSUE THREAD

**Issue by zdhsina** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#209]
- [ ] 我确认，我已经看过[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，并且提出的 Issue 是关于《提问的智慧》的翻译本身，而非某个软件。

uni-h5.es.js:6231  Uncaught TypeError: $el.querySelector is not a function
    at requestComponentObserver (uni-h5.es.js:6231:20)
    at addIntersectionObserver (uni-h5.es.js:6247:42)
    at ServiceIntersectionObserver.observe (uni-h5.es.js:4196:5)
    at observerContentScroll (wd-sticky.vue:1:1)
    at wd-sticky.vue:1:1
    at util.ts:1:1

**Comment by Geno1024** [comment]
"我确认，我已经看过[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，并且提出的 Issue 是关于《提问的智慧》的翻译本身，而非某个软件。"
