### ISSUE TITLE
唯有一台主机连接数据库不正常

### ISSUE THREAD

**Issue by hkyloveshe** [ryanhanwu/How-To-Ask-Questions-The-Smart-Way#9]
您好,我在配置面板时,发现一个情况,其余主机在连接数据库正常,唯一有一台经过多次测试仍然连接不上,报错信息如下:
2016-10-19 23:41:10 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2016-10-19 23:41:10 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-19 23:41:10 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-10-19 23:41:11 ERROR    db_transfer.py:561 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 553, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 211, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 56, in update_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 411, in _connect
    self._get_server_information()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 512, in _get_server_information
    packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1042, u"Can't get hostname for your address")
期间我检查了IPTABLES,数据库用户名权限等都没有问题.实在解决不了才发了这个ISSUE,望大佬抽空帮我看一眼.
&在面板前端发现个小问题,第一次填写节点列表里条目如果用了域名,会自动生成IP地址.之后再手动改IP会出现显示依然还是上次域名解析的IP.我看了数据库发现node表server变了,但是node_ip没有跟着变化,不知是不是偶然问题.

**Comment by chusiang** [comment]
@hkyloveshe 試著在發生問題的機器上，使用 `mysql -u <username> -h <hostname> -p` 來測測 mysql 的連線是否可以正常連線？

還有建議您把上面的問題排版一下，您可以參考 [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/) 一文，這樣別人會比較好懂。:P

**Comment by hkyloveshe** [comment]
问题已解决,感谢大佬的提醒,在breakwa11的底部发现其他问题解决方案
如果连接数据库遇到这个错误：Can't get hostname for your address，请在数据库服务器的 my.cnf 里 mysqld 添加如下设置
skip-name-resolve
然后重启数据库。
